# 检查或未检查的异常？

> 原文：<https://jenkov.com/tutorials/java-exception-handling/checked-or-unchecked-exceptions.html>

在 Java 中，基本上有两种类型的异常:检查异常和未检查异常。C#只有未检查的异常。已检查异常和未检查异常的区别在于:

1.  被检查的异常必须被显式捕获或传播，如[基本 try-catch-finally 异常处理](basic-try-catch-finally.html)中所述。未检查的异常没有这个要求。他们不需要被抓住或者被宣布扔出去。
    T3】
2.  Java 中的检查异常扩展了 java.lang.Exception 类。未检查的异常扩展 java.lang.RuntimeException。

对于检查和不检查，以及是否使用检查异常，有许多支持和反对的论点。我会在这篇文章中讨论最常见的论点。在此之前，让我先澄清一件事:

> 检查异常和未检查异常在功能上是等效的。对于已检查的异常，您所能做的一切都无法在未检查的异常中实现，反之亦然。

不管你选择检查还是不检查异常，这都是个人或组织风格的问题。没有一个在功能上比另一个更好。

## 简单的例子

在讨论检查异常和未检查异常的优缺点之前，我将向您展示它们在代码中的区别。下面是一个抛出检查异常的方法，以及另一个调用它的方法:

```

    public void storeDataFromUrl(String url){
        try {
            String data = readDataFromUrl(url);
        } catch (BadUrlException e) {
            e.printStackTrace();
        }
    }

    public String readDataFromUrl(String url)
    throws BadUrlException{
        if(isUrlBad(url)){
            throw new BadUrlException("Bad URL: " + url);
        }

        String data = null;
        //read lots of data over HTTP and return
        //it as a String instance.

        return data;
    }

```

正如您所看到的，readDataFromUrl()方法抛出了一个 BadUrlException。我自己已经创建了 BadUrlException。BadUrlException 是已检查的异常，因为它扩展了 java.lang.Exception:

```
    public class BadUrlException extends Exception {
        public BadUrlException(String s) {
            super(s);
        }
    }

```

如果 storeDataFromUrl()想要调用 readDataFromUrl()，它只有两个选择。它要么捕获 BadUrlException，要么将它向上传播到调用堆栈。上面列出的 storeDataFromUrl()捕捉异常。此 storeDataFromUrl()实现改为传播 BadUrlException:

```
    public void storeDataFromUrl(String url)
    throws BadUrlException{
        String data = readDataFromUrl(url);
    }

```

请注意 try catch 块是如何消失的，并添加了一个“throws BadUrlException”声明。现在，让我们看看它是如何处理未检查的异常的。首先，我将 BadUrlException 改为扩展 java.lang.RuntimeException:

```
    public class BadUrlException extends RuntimeException {
        public BadUrlException(String s) {
            super(s);
        }
    }

```

然后我将方法改为使用现在未检查的 BadUrlException:

```
    public void storeDataFromUrl(String url){
        String data = readDataFromUrl(url);
    }

    public String readDataFromUrl(String url) {
        if(isUrlBad(url)){
            throw new BadUrlException("Bad URL: " + url);
        }

        String data = null;
        //read lots of data over HTTP and
        //return it as a String instance.

        return data;
    }

```

注意 readDataFromUrl()方法不再声明它抛出 BadUrlException。storeDataFromUrl()方法也不必捕获 BadUrlException。storeDataFromUrl()方法仍然可以选择捕获异常，但它不再需要这样做，也不再需要声明它传播了异常。

## 检查或未检查的异常？

既然我们已经看到了检查异常和未检查异常在代码中的区别，让我们深入讨论一下支持和反对这两种异常的理由。

一些涉及异常的 Java 书籍(*)建议您对应用程序可以恢复的所有错误使用检查异常，对应用程序不能恢复的错误使用未检查异常。实际上，大多数应用程序必须从几乎所有异常中恢复，包括 NullPointerException、IllegalArgumentExceptions 和许多其他未检查的异常。失败的动作/事务将被中止，但应用程序必须保持活动，并准备好服务于下一个动作/事务。正常情况下，关闭应用程序唯一合法的时间是在启动期间。例如，如果一个配置文件丢失了，应用程序没有它就不能做任何有意义的事情，那么关闭应用程序是合法的。

(*) Suns Java 教程就是一个例子。

我给你的建议是要么只使用检查过的异常，要么只使用未检查过的异常。混合异常类型通常会导致混乱和不一致的使用。你当然要务实。做在你的情况下有意义的事情。

下面是支持和反对已检查和未检查异常的最常见参数列表。赞成一种类型的异常的论点通常反对另一种类型(赞成检查=反对未检查，赞成未检查=反对检查)。因此，参数只被列为支持检查的或未检查的异常。

1.  Pro 检查异常:
    编译器强制捕获或传播检查异常，使得忘记处理该异常变得更加困难。

2.  Pro Checked Exceptions:
    未检查的异常更容易忘记处理错误，因为编译器不会强制开发人员捕捉或传播异常(与 1 相反)。

3.  Pro 未检查的异常:
    在调用栈中向上传播的检查过的异常会使顶层方法变得混乱，因为这些方法需要声明抛出它们调用的方法抛出的所有异常。

4.  Pro Checked 异常:
    当方法没有声明它们可能抛出什么未检查的异常时，处理它们就变得更加困难。

5.  Pro 未检查的异常:
    抛出的检查异常成为方法接口的一部分，使得在类或接口的更高版本中添加或移除方法异常变得更加困难。

每一个论点都有相反的论点，我会在接下来的章节中讨论这些论点。

### 参数 1(专业检查异常):

Compiler enforced catching or propagation of checked exceptions makes it harder to forget the handling of that exception.

### 反驳:

当被迫捕捉或传播许多异常时，开发人员会冒险草率行事，只是写

```
try{
   callMethodThatThrowsException();
catch(Exception e){
}

```

从而有效地忽略误差。

T2】

### 参数 2(专业检查异常):

未检查的异常更容易忘记处理错误，因为编译器不会强制开发人员捕捉或传播异常。

### 反驳论点 1:

当被迫处理或传播被检查的异常时，这并不比草率的异常处理倾向更糟糕。

### 反驳论点 2:

在最近的一个大型项目中，我们决定使用未检查的异常。我从那个项目中获得的个人经验是:当使用未检查的异常时，任何方法都可能抛出异常。因此，无论我在代码的哪个部分工作，我总是合理地意识到异常。不仅仅是在检查异常被声明的时候。

此外，许多不声明任何已检查异常的标准 Java API 方法仍可能抛出未检查异常，如 NullPointerException 或 InvalidArgumentException。您的应用程序仍然需要处理这些未检查的异常。您可能会争辩说，存在检查异常的事实使得人们很容易忘记处理未检查的异常，因为它们没有被声明。

T2】

### 参数 3(支持未检查的异常):

在调用堆栈中向上传播的检查异常会使顶层方法变得混乱，因为这些方法需要声明抛出它们调用的方法抛出的所有异常。那就是。声明的异常聚集在调用堆栈中的方法上。示例:

```
    public long readNumberFromUrl(String url)
    throws BadUrlExceptions, BadNumberException{
        String data = readDataFromUrl(url);
        long number = convertData(data);
        return number;
    }

    private String readDataFromUrl(String url)
    throws BadUrlException {
       //throw BadUrlException if url is bad.
       //read data and return it.
    }

    private long convertData(String data)
    throws BadNumberException{
        //convert data to long.
        //throw BadNumberException if number isn't within valid range.
    }

```

正如您所看到的，readNumberFromUrl()需要声明抛出从 readDataFromUrl()和 converData()方法中抛出的 BadUrlException 和 BadNumberException。想象一下，在拥有数千个类的应用程序的顶层方法中，需要声明多少个异常。这可能会使受检查的异常传播变得非常痛苦。

### 反驳论点 1:

异常声明聚合在实际应用中很少发生。开发人员通常会使用异常包装来代替。这可能是这样的:

```
    public void readNumberFromUrl(String url)
    throws ApplicationException{
        try{
            String data = readDataFromUrl(url);
            long number = convertData(data);
        } catch (BadUrlException e){
            throw new ApplicationException(e);
        } catch (BadNumberException e){
            throw new ApplicationException(e);
        }
    }

```

如您所见，readNumberFromUrl()方法现在只声明抛出 ApplicationException。异常 BadUrlException 和 BadNumberException 被捕获并包装在一个更通用的 ApplicationException 中。这样，异常包装避免了异常声明聚合。

我个人的观点是，如果你所做的只是包装异常，而不提供任何额外的信息，为什么要包装它呢？try-catch 块只是不做任何事情的额外代码。让 ApplicationException、BadUrlException 和 BadNumberException 成为未检查的异常会更容易。以下是上述代码的未检查版本:

```
    public void readNumberFromUrl(String url){
        String data = readDataFromUrl(url);
        long number = convertData(data);
    }

```

如果您愿意，仍然可以包装未检查的异常。下面是未检查代码的包装版本。请注意 readNumberFromUrl()方法如何不声明抛出 ApplicationException，即使它抛出了该异常。

```
    public void readNumberFromUrl(String url)
        try{
            String data = readDataFromUrl(url);
            long number = convertData(data);
        } catch (BadUrlException e){
            throw new ApplicationException(
                "Error reading number from URL", e);
        } catch (BadNumberException e){
            throw new ApplicationException(
                "Error reading number from URL", e);
        }
    }

```

### 反驳论点 2:

另一种避免异常声明聚集到应用程序的调用堆栈中的常用技术是创建一个应用程序基础异常。应用程序中抛出的所有异常都必须是基本异常的子类。所有抛出异常的方法只需要声明抛出基异常。众所周知，抛出异常的方法也可能抛出异常的任何子类。这可能是这样的:

```
    public long readNumberFromUrl(String url)
    throws ApplicationException {
        String data = readDataFromUrl(url);
        long number = convertData(data);
        return number;
    }

    private String readDataFromUrl(String url)
    throws BadUrlException {
       //throw BadUrlException if url is bad.
       //read data and return it.
    }

    private long convertData(String data)
    throws BadNumberException{
        //convert data to long.
        //throw BadNumberException if number isn't within valid range.
    }

    public class ApplicationException extends Exception{ }
    public class BadNumberException   extends ApplicationException{}
    public class BadUrlException      extends ApplicationException{}

```

请注意 BadNumberException 和 BadUrlException 不再声明为 thrown，也不再被捕获和包装。它们是 ApplicationException 的子类，因此它们将在调用堆栈中向上传播。

我的看法和异常包装一样:如果应用程序中的所有方法都只是声明抛出 ApplicationException(base exception)，为什么不干脆让 application exception 不被选中，保存一些 try-catch 块，抛出 ApplicationExceptions 子句呢？

### 参数 4(专业检查异常)

当方法没有声明它们可能抛出什么未检查的异常时，处理它们就变得更加困难。没有声明，你就不知道这个方法会抛出哪些异常。因此，你可能不知道如何正确处理它们。当然，如果你能访问代码，并能看到方法会抛出什么异常，那就是例外。

### 反驳:

在大多数情况下，除了向用户显示一条错误消息、向日志中写入一条消息和/或回滚事务等，您无法对异常做任何事情。无论发生什么异常，在许多情况下你都会以同样的方式处理它。因此，应用程序通常有一些核心的和通用的错误处理代码。因此，确切知道可能会抛出什么异常并不重要。

### 参数 5(支持未检查的异常)

在方法上声明的检查异常成为类或接口协定的一部分。这使得以后在不破坏契约的情况下向方法添加新的异常变得更加困难。

### 反论点

如果方法使用基本异常，这不是问题。如果方法声明抛出基异常，则可以随意抛出新异常。唯一的要求是抛出的新异常是基本异常的子类。

同样，让所有可能抛出异常的方法声明抛出同一个基异常有什么价值？与您知道方法可能抛出未检查的异常相比，它是否使您能够更好地处理异常？

## 摘要

我曾经支持检查异常，但最近我开始改变我的想法。像 Rod Johnson (Spring Framework)、安德斯·海尔斯伯格(C#之父)、Joshua Bloch(有效的 Java，第 41 项:避免不必要的使用检查异常)和其他一些人让我重新思考检查异常的真正好处。最近，我们已经尝试在一个更大的项目中使用未检查的异常，它们工作得很好。错误处理集中在几个类中。我们不得不到处进行本地错误处理，而不是将异常传播到主错误处理代码。但不是在很多地方。我们的代码已经变得更具可读性，因为代码中没有 try-catch 块。换句话说，代码中无用的 catch-rethrow try-catch 块比检查异常要少得多。总而言之，我建议使用未检查的异常。至少在一个项目上试一试。我把原因总结如下:

*   未检查的异常不会用不必要的 try-catch 块使代码混乱。
*   未检查的异常不会使方法声明与聚集的异常声明混杂在一起。
*   根据我的经验，你更容易忘记处理未检查的异常的论点是不成立的。
*   以我的经验来看，更难知道如何处理未声明的异常的论点是不成立的。
*   未检查的异常完全避免了版本问题。

您或您的项目必须自己决定是使用检查的还是未检查的异常，或者两者都使用。下面是一个资源列表，其中也讨论了检查异常和未检查异常之间的决定。

检查异常与未检查异常的对比
[http://www.artima.com/intv/handcuffs.html](http://www.artima.com/intv/handcuffs.html)

詹姆斯·戈斯林检查异常
[http://www.artima.com/intv/solid.html](http://www.artima.com/intv/solid.html)

比尔·凡纳斯检查异常
[http://www.artima.com/interfacedesign/exceptions.html](http://www.artima.com/interfacedesign/exceptions.html)

布鲁斯·埃克尔检查异常
[http://www.artima.com/intv/typingP.html](http://www.artima.com/intv/typingP.html)

设计异常(比尔·凡纳斯-www.artima.com)
[http://www.artima.com/designtechniques/desexcept.html](http://www.artima.com/designtechniques/desexcept.html)

[有效 Java](http://www.amazon.co.uk/exec/obidos/redirect?link_code=ur2&camp=1634&tag=jenkovdevelop-21&creative=6738&path=ASIN/0201310058/qid=1124382514/sr=1-1/ref=sr_1_3_1)