# Java IO:异常处理

> 原文：<https://jenkov.com/tutorials/java-io/io-exception-handling.html>

当您使用完流和读取器/写入器时，需要正确关闭它们。这是通过调用`close()`方法来完成的。这需要一点思考。看看这段代码:

```
InputStream input = new FileInputStream("c:\\data\\input-text.txt");

int data = input.read();
while(data != -1) {
  //do something with data...
  doSomethingWithData(data);

  data = input.read();
}
input.close();

```

这段代码乍一看还不错。但是如果从`doSomethingWithData()`方法内部抛出异常会发生什么呢？没错！`InputStream`永不关闭！

为了避免这种情况，您可以将代码重写为:

```
InputStream input = null;

try{
  input = new FileInputStream("c:\\data\\input-text.txt");

  int data = input.read();
  while(data != -1) {
      //do something with data...
      doSomethingWithData(data);

      data = input.read();
  }
}catch(IOException e){
  //do something with e... log, perhaps rethrow etc.
} finally {
  if(input != null) input.close();
}

```

注意`InputStream`现在是如何在 finally 子句中关闭的。无论 try 块中发生什么，finally 子句都将被执行。因此`InputStream`将一直关闭。

但是如果`close()`抛出异常会发生什么呢？假设溪流已经关闭了？为了捕捉这种情况，您还必须将对`close()`的调用包装在一个 try-catch 块中，就像这样:

```
} finally {
  try{
    if(input != null) input.close();
  } catch(IOException e){
    //do something, or ignore.
  }
}

```

正确处理`InputStream`(或 OutputStream)迭代的代码可能会非常糟糕，正如您所看到的，一旦您在其中获得了正确的异常处理。这种丑陋的异常处理代码在你的代码中一遍又一遍地重复并不是特别好。着急的人偷工减料，跳过异常处理怎么办？

此外，假设从`doSomethingWithData()`开始首先抛出一个异常。第一个`catch`子句将捕获该异常，然后 finally 子句将尝试关闭`InputStream`。但是，如果从`input.close()`方法中也抛出一个异常，会发生什么呢？这两个异常中的哪一个应该在调用堆栈中向上传播？

幸运的是，有一种方法可以解决这个问题。这个解决方案叫做“异常处理模板”。创建一个异常处理模板，在使用后正确关闭您的流。这个模板只需编写一次，就可以在整个代码中重用。简单明了。要了解更多信息，请访问 Java 中的[异常处理模板](http://tutorials.jenkov.com/java-exception-handling/exception-handling-templates.html)。

## Java 7 中的 Java IO 异常处理

从 Java 7 开始，Java 包含了一个新的异常处理机制，叫做“资源尝试”。这种异常处理机制特别针对当您正在使用需要在使用后正确关闭的资源时的异常处理，如`InputStream`、`OutputStream`等。你可以在我的教程中读到更多关于 Java 7 中的资源的。